### PR TITLE
Add build job to check pipeline

### PR DESCRIPTION
**Pull request by albinvass**

### CODE REVIEW

**Comment by albinvass** [comment]
recheck

**Comment by albinvass** [comment]
recheck

**Comment by albinvass** [comment]
recheck

**Comment by albinvass** [comment]
recheck

**Comment by albinvass** [comment]
recheck

**Comment by albinvass** [comment]
recheck

**Comment by albinvass** [comment]
recheck

**Comment by albinvass** [comment]
recheck

**Comment by albinvass** [comment]
recheck

**Review by Vilddjur — APPROVED** [review]

**Pull request merged**
